global:
  scrape_interval: 15s
  evaluation_interval: 10s
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "myapp"
    scrape_interval: 5s
    static_configs:
      - targets: ["myapp:8000"]
