global:
  scrape_interval: 15s
  evaluation_interval: 10s
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "weather-app"
    scrape_interval: 5s
    static_configs:
      - targets: ["weather-app:8000"]
